config/routes.rb
Rails.application.routes.draw do
  namespace :searches do
    resource :product_categories, only: :show
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "businesses#index"

  resources :businesses do
    member do
      get 'dashboard'
    end
    
    resources :customers
    resources :product_categories
    resources :products
  end

  get "/settings/account", to: "settings#index", as: :settings
  get "/settings/account_information", to: "settings#account_information", as: :account_information_settings
  get "/settings/password", to: "settings#password", as: :password_settings
  get "/settings/email", to: "settings#email", as: :email_settings
  get "/settings/name", to: "settings#name", as: :name_settings
  get "/settings/country", to: "settings#country", as: :country_settings
  patch "/settings/profile", to: "settings#update_profile", as: :update_profile_settings
  get "/settings/deactivate_account", to: "settings#deactivate_account", as: :deactivate_account_settings
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :authenticate!
  before_action :find_business, only: %w[show edit update destroy dashboard]

  def index
    @businesses = current_account.businesses.ordered
  end

  def show
    @accordion_businesses = current_account.businesses.ordered - [@business]
  end

  def new
    @business = Business.new
  end

  def create
    @business = current_account.businesses.build(business_params)

    if @business.save
      respond_to do |format|
        format.html { redirect_to @business, notice: "Business created successfully" }
        # format.turbo_stream { flash.now[:notice] = 'Podcast created successfully' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    
  end

  def update
    if @business.update(business_params)   
      respond_to do |format| 
        format.html { redirect_to @business, notice: "Business updated successfully" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    
  end

  def dashboard
    @accordion_businesses = current_account.businesses.ordered - [@business]
  end

  private

    def business_params
      params.require(:business).permit(:name, :description, :tax_rate, :logo, :currency)
    end

    def find_business
      @business = current_account.businesses.find(params[:id])
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<div class="p-6 bg-white border border-gray-8400 rounded-xl shadow-md dark:bg-gray-800 dark:border-gray-700">
    <%= link_to dashboard_business_path(business) do %>
        <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 hover:text-gray-700 dark:text-white"><%= business.name %></h5>
    <% end %>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= business.description.truncate(100) %></p>
    
    <%= link_to dashboard_business_path(business), class: "inline-flex items-center text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" do %>
        Show business
        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
    <% end %>
</div>

app/views/businesses/_form.html.erb
<div class="px-6 py-5">
    <%= form_with(model: [business], data: { turbo: false }, class: "w-full") do |form| %>
        <div class="mb-6">
            <%= form.label "name", class: "block text-sm font-semibold" %>
            <%= form.text_field :name, class: "focus:ring-black/80 focus:border-black/80 mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800", required: true %>
        </div>

        <div class="mb-6">
            <%= form.label "description", class: "block text-sm font-semibold" %>
            <%= form.text_area :description, class: "focus:ring-black/80 focus:border-black/80 mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800" %>
        </div>

        <div class="mb-6">
            <%= form.label "currency", class: "block text-sm font-semibold" %>
            <%= select_tag 'business[currency]', options_for_select(Business::CURRENCIES.keys, @business.currency), 
            class: "mt-2 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 cursor-pointer" %>
        </div>

        <div class="mb-6">
            <%= form.label "tax_rate (optional)", class: "block text-sm font-semibold" %>
            <%= form.text_field :tax_rate, class: "focus:ring-black/80 focus:border-black/80 mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800" %>
        </div>

        <div class="mb-6">
            <%= form.label "Business logo (optional)", class: "block text-sm font-semibold" %>
            <%= form.file_field :logo, class: "mt-2 block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400", data: { "profile-edit-form-target": "avatarFile", action: "change->profile-edit-form#avatarChanged" } %>
        </div>

        <%= form.submit "Save", class: "w-full px-8 py-3 cursor-pointer font-semibold text-sm rounded-lg text-white bg-black/90 hover:bg-black/80 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-black/60 dark:bg-emerald-400 dark:hover:bg-emerald-500 dark:text-gray-900 dark:focus:ring-emerald-400 dark:focus:ring-offset-current" %>
    <% end %>
</div>

app/views/businesses/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<%= render 'businesses/components/sidebar' %>

<div class="p-4 lg:ml-18.5rem mt-4.4rem bg-white rounded-3xl h-[calc(100vh-5.5rem)] shadow-md m-4 border border-gray-300">

    <h1 class="font-bold text-xl mb-2">Dashboard</h1>

    <p>Dashboard content goes here</p>
</div>

app/views/businesses/edit.html.erb
<%= render 'layouts/modal_dialog' do %>
  <div data-action="turbo:submit-end->dialog#submitEnd">
    <h1 class="font-semibold text-xl sm:text-xl md:text-xl p-3 border-b">Edit Business</h1>
    <%= render "form", business: @business %>
  </div>
<% end %>

app/views/businesses/index.html.erb
<% provide(:title, "My businesses") %>

<div class=" h-[calc(100vh-4.1rem)] wrapper bg-[#d9d9d9]">
    <div class="p-4">

        <div class="flex gap-2 items-center justify-between">
            
            <h1 class="font-bold text-2xl py-5">My businesses</h1>

            <%= link_to new_business_path, class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-gray-900 rounded-lg hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800 gap-1", data: {action: "click->dialog#open", turbo_frame: :modal} do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>

                Add new business
            <% end %>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
            <%= render @businesses %>
        </div>
    </div>
</div>

app/views/businesses/new.html.erb
<%= render 'layouts/modal_dialog' do %>
  <div data-action="turbo:submit-end->dialog#submitEnd">
    <h1 class="font-semibold text-xl sm:text-xl md:text-xl p-3 border-b">New Business</h1>
    <%= render "form", business: @business %>
  </div>
<% end %>

app/views/businesses/show.html.erb
<% provide(:title, sanitize(@business.name)) %>
<%= render 'businesses/components/sidebar' %>

<div class="p-4 lg:ml-18.5rem mt-4.4rem bg-white rounded-3xl h-[calc(100vh-5.5rem)] m-4 shadow-md">
    <div class="flex gap-2 items-center justify-between">
        <div>
            <h1 class="font-bold text-xl">Profile</h1>
            <p>Business profile and information</p>
        </div>

        <%= link_to edit_business_path(@business), class: "text-gray-900 bg-white border border-gray-900 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-2 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700", data: {action: "click->dialog#open", turbo_frame: :modal} do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
            </svg>
            
        <% end %>
    </div>

    <div class="mt-5 border rounded-lg">
        <ul>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <span class="font-semibold w-32">
                        Name
                    </span>

                    <span>
                        <%= @business.name %>
                    </span>
                </div>
            </li>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <span class="font-semibold w-32">
                        Description
                    </span>

                    <span>
                        <% if @business.description.present? %>
                            <%= @business.description %>
                        <% else %>
                            <p>Nil</p>
                        <% end %>
                    </span>
                </div>
            </li>
            <li>
                <div class="flex gap-20 p-4">
                    <span class="font-semibold w-32">
                        Currency
                    </span>

                    <span>
                        <%= @business.currency %> (<%= @business.currency_symbol %>)
                    </span>
                </div>
            </li>
        </ul>
    </div>
</div>