config/routes.rb
Rails.application.routes.draw do
  namespace :searches do
    resource :product_categories, only: :show
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "businesses#index"

  resources :businesses do
    member do
      get 'dashboard'
    end
    
    resources :customers
    resources :product_categories
    resources :products
  end

  get "/settings/account", to: "settings#index", as: :settings
  get "/settings/account_information", to: "settings#account_information", as: :account_information_settings
  get "/settings/password", to: "settings#password", as: :password_settings
  get "/settings/email", to: "settings#email", as: :email_settings
  get "/settings/name", to: "settings#name", as: :name_settings
  get "/settings/country", to: "settings#country", as: :country_settings
  patch "/settings/profile", to: "settings#update_profile", as: :update_profile_settings
  get "/settings/deactivate_account", to: "settings#deactivate_account", as: :deactivate_account_settings
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate!
  before_action :ensure_profile_exists, only: [:name, :country, :update_profile]

  def index
  end

  def account_information
  end

  def password
  end

  def email
  end

  def name
  end

  def country
  end

  def deactivate_account
  end

  def update_profile
    if @profile.update(profile_params)
      flash[:notice] = "Profile updated successfully."
      redirect_to account_information_settings_path
    else
      flash.now[:alert] = @profile.errors.full_messages.join(", ")
      render action_name, status: :unprocessable_entity
    end
  end

  private

  def ensure_profile_exists
    @profile = current_account.profile || current_account.create_profile
  end

  def profile_params
    params.require(:profile).permit(:name, :avatar, :country)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/account_information.html.erb
<div class="w-full h-[calc(100vh-4.5rem)] wrapper">
  <div class="max-w-screen-xl mx-auto">
    <div class="max-w-screen-2xl grid grid-cols-1 md:grid-cols-[225px_minmax(100px,_1fr)] xl:grid-cols-[300px_minmax(100px,_1fr)]  h-[calc(100vh-4.1rem)] wrapper px-4">
      <div class="border-r pt-4">
        
        <%= render 'settings/components/settings_sidebar' %>
        
      </div>

      <div>
        <div class="flex gap-10 items-center py-4 pl-6">
            <%= link_to settings_path do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75 3 12m0 0 3.75-3.75M3 12h18" />
                </svg>
            <% end %>
            <h2 class="font-bold text-2xl">Account information</h2>
        </div>

        <ul>
            <li class="">
                <%= link_to name_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-100 px-6 p-2" do %>

                    <div class="flex items-center gap-2">
                        <span>
                            <% if current_account.profile.avatar.attached? %>
                                <%= image_tag(current_account.profile.avatar, class: "w-14 h-14 object-cover rounded-full border-2 border-white", alt: "profile picture", data: { "profile-edit-form-target": "avatarPreview" }) %>
                            <% else %>
                                <%= image_tag('others/default avatar.png', class: "w-14 h-14 object-cover rounded-full border-2 border-white border-gray-800", alt: "profile picture", data: { "profile-edit-form-target": "avatarPreview" }) %>
                            <% end %>
                        </span>
                        <div>
                            <p><%= current_account.profile.name %></p>
                        </div>
                    </div>

                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                        </svg>
                    </span>
                <% end %>
            </li>

            <li class="">
                <%= link_to rodauth.change_login_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-100 px-6 p-2" do %>

                <div>
                    <p>Email</p>
                    <p class="text-sm text-gray-600"><%= current_account.email %> (<%= current_account.status %>)</p>
                </div>

                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>
                </span>
                <% end %>
            </li>

            <li class="">
                <%= link_to country_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-100 px-6 p-2" do %>

                <div>
                    <p>Country</p>
                    <% if current_account.profile.country.present? %>
                        <p class="text-sm text-gray-600"><%= current_account.profile.country_label %></p>
                    <% else %>
                        <p class="text-sm text-gray-600">Nil</p>
                    <% end %>
                </div>

                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                    </svg>
                </span>
                <% end %>
            </li>

            <li class="border-t border-b">
                <%= link_to account_information_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-100 px-6 p-2" do %>

                    <div>
                        <p>Account creation</p>
                        <p class="text-sm text-gray-600"><%= current_account.profile.created_at.strftime("%b %d, %Y, %I:%M:%S %p")
                        %></p>
                    </div>

                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                        </svg>
                    </span>
                <% end %>
            </li>

            <li>
                <%= link_to account_information_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-100 px-6 p-2" do %>

                    <div>
                        <p>Prefered language</p>
                        <p class="text-sm text-gray-600">English</p>
                    </div>

                    <span>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                        </svg>
                    </span>
                <% end %>
            </li>

        </ul>
      </div>
    </div>
  </div>
</div>

app/views/settings/country.html.erb
<div class="w-full h-[calc(100vh-4.5rem)] wrapper">
  <div class="max-w-screen-xl mx-auto">
    <div class="max-w-screen-2xl grid grid-cols-1 md:grid-cols-[225px_minmax(100px,_1fr)] xl:grid-cols-[300px_minmax(100px,_1fr)]  h-[calc(100vh-4.1rem)] wrapper px-4">
        <div class="border-r pt-4">
            <%= render 'settings/components/settings_sidebar' %>
        </div>

        <div>
            <div class="flex gap-10 items-center py-4 pl-6">
                <%= link_to account_information_settings_path do %>
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75 3 12m0 0 3.75-3.75M3 12h18" />
                    </svg>
                <% end %>
                <h2 class="font-bold text-2xl">Update your country</h2>
            </div>

            <div class="px-6 p-2">
                <%= form_with model: current_account.profile, url: update_profile_settings_path, method: :patch, data: { turbo_frame: "_top", controller: "profile-edit-form" }, class: "w-full" do |form| %>
                    <%= render "settings/components/form", form: form do %>
                        <div class="mb-6">
                        <%= form.label :country, class: "block text-sm font-semibold" %>
                        <%= form.select :country, @profile.countries.invert, { include_blank: "Select your country?", required: true, value: current_account.profile.country }, 
                            { class: "mt-2 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 cursor-pointer" 
                            } %>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>
        

app/views/settings/index.html.erb
<div class="w-full h-[calc(100vh-4.5rem)] wrapper">
  <div class="max-w-screen-xl mx-auto">
    <div class="max-w-screen-2xl grid grid-cols-1 md:grid-cols-[225px_minmax(100px,_1fr)] xl:grid-cols-[300px_minmax(100px,_1fr)]  h-[calc(100vh-4.1rem)] wrapper px-4">
      <div class="border-r pt-4">
        
        <%= render 'settings/components/settings_sidebar' %>
        
      </div>

      <div>
        <h2 class="font-bold text-2xl p-4">Your Account</h2>

        <p class="text-sm ml-4 mb-3">See information about your account or learn about your account deactivation options</p>

        <ul>
          <li class="">
            <%= link_to account_information_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-200 p-3 px-8" do %>

              <div class="flex gap-5 items-center">
                <span>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
                  </svg>
                </span>
                <div>
                  <p>Account information</p>
                  <p class="text-sm text-gray-600">See your account information like your name and email address.</p>
                </div>
              </div>

              <span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                </svg>
              </span>
            <% end %>
          </li>

          <li class="">
            <%= link_to password_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-200 p-3 px-8" do %>

              <div class="flex gap-5 items-center">
                <span>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z" />
                  </svg>
                </span>
                <div>
                  <p>Change your password</p>
                  <p class="text-sm text-gray-600">Change your password at any time.</p>
                </div>
              </div>

              <span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                </svg>
              </span>
            <% end %>
          </li>

          <li class="">
            <%= link_to deactivate_account_settings_path, class: "inline-flex justify-between items-center w-full hover:bg-gray-200 p-3 px-8" do %>

              <div class="flex gap-5 items-center">
                <span>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15.182 16.318A4.486 4.486 0 0 0 12.016 15a4.486 4.486 0 0 0-3.198 1.318M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM9.75 9.75c0 .414-.168.75-.375.75S9 10.164 9 9.75 9.168 9 9.375 9s.375.336.375.75Zm-.375 0h.008v.015h-.008V9.75Zm5.625 0c0 .414-.168.75-.375.75s-.375-.336-.375-.75.168-.75.375-.75.375.336.375.75Zm-.375 0h.008v.015h-.008V9.75Z" />
                  </svg>
                </span>
                <div>
                  <p>Deactivate your account</p>
                  <p class="text-sm text-gray-600">Find out how to permanently delete your account.</p>
                </div>
              </div>

              <span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                </svg>
              </span>
            <% end %>
          </li>

        </ul>
      </div>
    </div>
  </div>
</div>

app/views/settings/name.html.erb
<div class="w-full h-[calc(100vh-4.5rem)] wrapper">
  <div class="max-w-screen-xl mx-auto">
    <div class="max-w-screen-2xl grid grid-cols-1 md:grid-cols-[225px_minmax(100px,_1fr)] xl:grid-cols-[300px_minmax(100px,_1fr)]  h-[calc(100vh-4.1rem)] wrapper px-4">
      <div class="border-r pt-4">
        <%= render 'settings/components/settings_sidebar' %>
      </div>

      <div>
        <div class="flex gap-10 items-center py-4 pl-6">
          <%= link_to account_information_settings_path do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 15.75 3 12m0 0 3.75-3.75M3 12h18" />
            </svg>
          <% end %>
          <h2 class="font-bold text-2xl">Change your name and avatar</h2>
        </div>

        <div class="px-6 p-2">
          <%= form_with model: current_account.profile, url: update_profile_settings_path, method: :patch, data: { turbo_frame: "_top", controller: "profile-edit-form" }, class: "w-full" do |form| %>
            <%= render "settings/components/form",  form: form do |f| %>
              <div class="mb-6">
                <%= f.label :select_avatar, class: "block text-sm font-semibold" %>
                <%= f.file_field :avatar, class: "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 hidden", data: { "profile-edit-form-target": "avatarFile", action: "change->profile-edit-form#avatarChanged" } %>

                <div class="mt-2">
                  <%= render 'settings/components/form_avatar_preview' %>
                </div>
              </div>

              <div class="mb-6">
                <%= f.label :name, class: "block text-sm font-semibold" %>
                <%= f.text_field :name, required: true, value: current_account.profile.name, class: "focus:ring-black/80 focus:border-black/80 mt-2 text-sm w-full px-3 py-2 border rounded-md dark:bg-gray-900 dark:text-gray-100 dark:focus:bg-gray-800 #{rodauth.field_error('name') ? 'border-red-600 focus:ring-red-600 focus:border-red-600 dark:border-red-400 dark:focus:ring-red-400' : 'border-gray-300 dark:border-gray-700 dark:focus:border-emerald-400 dark:focus:ring-emerald-400'}" %>
                <%= content_tag(:span, rodauth.field_error("name"), class: "block mt-1 text-red-600 text-xs dark:text-red-400", id: "name_error_message") if rodauth.field_error("name") %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>