config/routes.rb
Rails.application.routes.draw do
  namespace :searches do
    resource :product_categories, only: :show
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "businesses#index"

  resources :businesses do
    member do
      get 'dashboard'
    end
    
    resources :customers
    resources :product_categories
    resources :products
  end

  get "/settings/account", to: "settings#index", as: :settings
  get "/settings/account_information", to: "settings#account_information", as: :account_information_settings
  get "/settings/password", to: "settings#password", as: :password_settings
  get "/settings/email", to: "settings#email", as: :email_settings
  get "/settings/name", to: "settings#name", as: :name_settings
  get "/settings/country", to: "settings#country", as: :country_settings
  patch "/settings/profile", to: "settings#update_profile", as: :update_profile_settings
  get "/settings/deactivate_account", to: "settings#deactivate_account", as: :deactivate_account_settings
end

app/models/product.rb
class Product < ApplicationRecord
  before_save :clear_irrelevant_price_fields

  validates :name, presence: true, length: { minimum: 5, maximum: 200 }
  validates :description, length: { maximum: 200 }
  validates :product_category, presence: true
  validate :validate_price_fields

  belongs_to :business, counter_cache: :products_count
  belongs_to :product_category, counter_cache: :products_count
  belongs_to :account, counter_cache: :products_count

  scope :ordered, -> { order(id: :desc) }

  private

    def clear_irrelevant_price_fields
      if negotiable_changed?
        if negotiable?
          # If negotiable, clear fixed_price
          self.fixed_price = nil
        else
          # If non-negotiable, clear min_price and max_price
          self.min_price = nil
          self.max_price = nil
        end
      end
    end

    def validate_price_fields
      if negotiable?
        errors.add(:min_price, "can't be blank") if min_price.blank?
        errors.add(:max_price, "can't be blank") if max_price.blank?
      else
        errors.add(:fixed_price, "can't be blank") if fixed_price.blank?
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate!
  before_action :find_product, only: %w[show edit update destroy]
  before_action :find_business
  before_action :find_category
  before_action :find_sidebar_businesses

  def index
    @products = @business.products.ordered
    @total_products = @business.products_count
    @pagy, @products = pagy(@products, limit: 30)
  end

  def show
    
  end

  def new
    @product = Product.new
  end

  def create
    @product = @business.products.build(product_params)
    @product.account = current_account

    if @product.save
      respond_to do |format|
        format.html { redirect_to business_products_path(@business), notice: "Product created successfully" }
        # format.turbo_stream { flash.now[:notice] = 'product created successfully' }
      end
    else
      flash.now[:alert] = "Failed to create product. Please check the errors below."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      respond_to do |format|
        format.html { redirect_to business_product_path(@business, @product), notice: "Product updated successfully" }
        # format.turbo_stream { flash.now[:notice] = 'product updated successfully' }
      end
    else
      flash.now[:alert] = "Failed to update product. Please check the errors below."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to business_products_path(@business), notice: "Product deleted successfully" }
    end
  end

  private

  def product_params
    params.expect(product: [
      :name, 
      :description, 
      :negotiable, 
      :stock_quantity, 
      :fixed_price, 
      :min_price, 
      :max_price,  
      :product_category_id
    ])
  end

  def find_business
    @business = Business.find(params[:business_id])
  end

  def find_category
    @category = ProductCategory.find_by(id: params[:product_category_id])
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def find_sidebar_businesses
    @accordion_businesses = current_account.businesses.ordered - [@business]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<% provide(:title, "Edit product - #{@business.name}") %>

<%= render 'businesses/components/sidebar' %>

<div class="p-4 lg:ml-18.5rem mt-4.4rem bg-white rounded-3xl shadow-md m-4 border">
    <nav class="flex mb-5" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
            <li class="inline-flex items-center">
                <%= link_to businesses_path, class: "inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-600 dark:text-gray-400 dark:hover:text-white" do %>
                    <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
                    </svg>
                    My businesses
                <% end %>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <%= link_to @business.name, dashboard_business_path(@business), class: "ms-1 text-sm font-medium text-gray-700 hover:text-gray-600 md:ms-2 dark:text-gray-400 dark:hover:text-white" %>
                </div>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <%= link_to 'Products', business_products_path(@business), class: "ms-1 text-sm font-medium text-gray-700 hover:text-gray-600 md:ms-2 dark:text-gray-400 dark:hover:text-white" %>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">New product</span>
                </div>
            </li>
        </ol>
    </nav>

    <div class="flex gap-2 items-center mb-2">
        <%= link_to sanitize("&larr;"), business_products_path(@business) %>
        <h1 class="font-semibold text-xl sm:text-xl md:text-xl p-3">Edit product</h1>
    </div>

    <%= render 'form', business: @business, product: @product %>
    
</div>

app/views/products/index.html.erb
<% provide(:title, "Products - #{@business.name}") %>

<%= render 'businesses/components/sidebar' %>

<div class="p-4 lg:ml-18.5rem mt-4.4rem bg-white rounded-3xl shadow-md m-3 border">
    <nav class="flex mb-5" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
            <li class="inline-flex items-center">
                <%= link_to businesses_path, class: "inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-600 dark:text-gray-400 dark:hover:text-white" do %>
                    <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
                    </svg>
                    My businesses
                <% end %>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <%= link_to @business.name, dashboard_business_path(@business), class: "ms-1 text-sm font-medium text-gray-700 hover:text-gray-600 md:ms-2 dark:text-gray-400 dark:hover:text-white" %>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400">Products</span>
                </div>
            </li>
        </ol>
    </nav>

    <div class="flex gap-2 items-center justify-between mb-3">
        <div class="flex gap-2 items-center">
            <%= link_to sanitize("&larr;"), dashboard_business_path(@business) %>
            <h1 class="font-bold text-xl">Products <span class="bg-gray-100 text-gray-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-gray-700 dark:text-gray-300"><%= @total_products %></span></h1>
        </div>

        <%= link_to new_business_product_path(@business), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-gray-900 rounded-lg hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800 gap-1" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>

            Add new product
        <% end %>
    </div>

    <% if params[:page] %>
        <h2 class="font-bold text-l mb-3">Page: <%= params[:page] %></h2>
    <% end %>


    <% if @products.none? %>
      <%= render "products/components/empty_state" %>
    <% else %>
        <%= turbo_frame_tag "products" do %>
            <div class="relative overflow-x-auto border rounded-3xl">
                
                <form class="m-5">
                    <div class="flex">
                        
                        <div class="relative w-full">
                            <input type="search" id="search-dropdown" class="rounded-3xl block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-e-3xllg rounded-s-gray-100 rounded-s-2 border border-gray-300 focus:ring-gray-500 focus:border-gray-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-gray-500" placeholder="Search" required />

                            <label for="search-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Your Email</label>
                            <!-- Modal toggle -->
                            <button data-modal-target="authentication-modal" data-modal-toggle="authentication-modal" class="absolute top-0 end-0 p-2.5 h-full text-sm font-medium text-white bg-gray-700 rounded-e-3xl border border-gray-700 hover:bg-gray-800 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800" type="button">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 1 1-3 0m3 0a1.5 1.5 0 1 0-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-9.75 0h9.75" />
                                </svg>
                            </button>
                        </div>
                    </div>
                </form>
                
                <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3 flex items-center gap-1">
                                <span>Name</span>
                                <%= link_to '#' do %>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                                    </svg>
                                <% end %>
                            </th>
                            <th scope="col" class="px-6 py-3">
                                <span class="flex items-center gap-1">
                                    <span>Negotiable?</span>
                                    <%= link_to '#' do %>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                                        </svg>
                                    <% end %>
                                </span>
                            </th>
                            <th scope="col" class="px-6 py-3">
                                <span class="flex items-center gap-1">
                                    <span>Min Price</span>
                                    <%= link_to '#' do %>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                                        </svg>
                                    <% end %>
                                </span>
                            </th>
                            <th scope="col" class="px-6 py-3">
                                <span class="flex items-center gap-1">
                                    <span>Max Price</span>
                                    <%= link_to '#' do %>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                                        </svg>
                                    <% end %>
                                </span>
                            </th>
                            <th scope="col" class="px-6 py-3">
                                Category
                            </th>
                            <th scope="col" class="px-6 py-3">
                                <span class="flex items-center gap-1">
                                    <span>Stock Quantity</span>
                                    <%= link_to '#' do %>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                                        </svg>
                                    <% end %>
                                </span>
                            </th>
                            <th scope="col" class="px-6 py-3">
                                <span class="flex items-center gap-1">
                                    <span>Sales</span>
                                    <%= link_to '#' do %>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M3 7.5 7.5 3m0 0L12 7.5M7.5 3v13.5m13.5 0L16.5 21m0 0L12 16.5m4.5 4.5V7.5" />
                                        </svg>
                                    <% end %>
                                </span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <%= render @products %>
                    </tbody>
                </table>
            </div>
        <% end %>

        <% if @pagy.next %>
            <div class="my-5 flex justify-center md:justify-end">
                <%== pagy_nav(@pagy, class: "ml-auto") %>
            </div>
        <% end %>
    <% end %>
</div>

app/views/products/show.html.erb
<% provide(:title, sanitize(@product.name)) %>

<%= render 'businesses/components/sidebar' %>

<div class="p-4 lg:ml-18.5rem mt-4.4rem bg-white rounded-3xl m-3 border border-gray-300 shadow-md">
    <nav class="flex mb-5" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
            <li class="inline-flex items-center">
                <%= link_to businesses_path, class: "inline-flex items-center text-sm font-medium text-gray-700 hover:text-gray-600 dark:text-gray-400 dark:hover:text-white" do %>
                    <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
                    </svg>
                    My businesses
                <% end %>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <%= link_to @business.name, dashboard_business_path(@business), class: "ms-1 text-sm font-medium text-gray-700 hover:text-gray-600 md:ms-2 dark:text-gray-400 dark:hover:text-white" %>
                </div>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <%= link_to 'Products', business_products_path(@business), class: "ms-1 text-sm font-medium text-gray-700 hover:text-gray-600 md:ms-2 dark:text-gray-400 dark:hover:text-white" %>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <span class="ms-1 text-sm font-medium text-gray-500 md:ms-2 dark:text-gray-400"><%= @product.name %></span>
                </div>
            </li>
        </ol>
    </nav>

    <div class="flex gap-2 items-center justify-between mb-3">
        <div class="flex gap-2 items-center mb-2">
            <%= link_to sanitize("&larr;"), business_products_path(@business) %>
            <h1 class="font-bold text-xl"><%= @product.name %></h1>
        </div>

        <div class="flex">
            <%= link_to edit_business_product_path(@business, @product), class: "text-gray-900 bg-white border border-gray-900 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-2 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                </svg>
            <% end %>

            <%= link_to business_product_path(@business, @product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-gray-900 bg-white border border-gray-900 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-2 py-2 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>
            <% end %>
        </div>
    </div>

    <%= render 'products/components/tabs' %>

    <div class="mt-5 border rounded-3xl">
        <ul>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <h6 class="font-semibold w-32">
                        Name
                    </h6>

                    <span>
                        <%= @product.name %>
                    </span>
                </div>
            </li>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <h6 class="font-semibold w-32">
                        Description
                    </h6>

                    <span>
                        <% if @product.description.present? %>
                            <%= @product.description %>
                        <% else %>
                            <p>Nil</p>
                        <% end %>
                    </span>
                </div>
            </li>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <h6 class="font-semibold w-32">
                        Negotiable?
                    </h6>

                    <span>
                        <%= @product.negotiable ? "Yes" : "No" %>
                    </span>
                </div>
            </li>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <h6 class="font-semibold w-32">
                        Category
                    </h6>

                    <span>
                        <%= link_to @product.product_category.name, business_product_category_path(@business, @product.product_category) %>
                    </span>
                </div>
            </li>
            <% if @product.negotiable? %>
                <li>
                    <div class="flex gap-20 border-b p-4">
                        <h6 class="font-semibold w-32">
                            Min price
                        </h6>

                        <span>
                            <%= @product.min_price %>
                        </span>
                    </div>
                </li>
                <li>
                    <div class="flex gap-20 border-b p-4">
                        <h6 class="font-semibold w-32">
                            Max price
                        </h6>

                        <span>
                            <%= @product.max_price %>
                        </span>
                    </div>
                </li>
            <% else %>
                <li>
                    <div class="flex gap-20 border-b p-4">
                        <h6 class="font-semibold w-32">
                            Price
                        </h6>

                        <span>
                            <%= @product.fixed_price %>
                        </span>
                    </div>
                </li>
            <% end %>
            <li>
                <div class="flex gap-20 border-b p-4">
                    <h6 class="font-semibold w-32">
                        Stock quantity
                    </h6>

                    <span>
                        <%= @product.stock_quantity %>
                    </span>
                </div>
            </li>
            <li>
                <div class="flex gap-20 p-4">
                    <h6 class="font-semibold w-32">
                        Sales
                    </h6>

                    <span>
                        250
                    </span>
                </div>
            </li>
        </ul>
    </div>
    
</div>